USE [MedicalTourism]
GO

/****** Object:  Table [dbo].[Country]    Script Date: 5/6/2015 7:05:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Country1](
	[CO_NAME] [nchar](40) NOT NULL,
 CONSTRAINT [PK_Country1] PRIMARY KEY CLUSTERED 
(
	[CO_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

